Parameters:
  Instancename:
    Type: String
    Description: Enter instance name
  Azone:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - ap-northeast-1
Mappings:
  Mapname:
    us-east-1:
      AMI: 'ami-0756fbca465a59a30'
    ap-northeast-1:
      AMI: 'ami-0ccdbc8c1cb7957be'

Resources:
  Myinstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [Mapname, !Ref Azone, AMI]
      SecurityGroups:
        - !Ref Secgroup1
        - !Ref Secgroup2
      Tags:
        - Key: Name
          Value: !Ref Instancename
  Secgroup1:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: test security group
      GroupName: testsg1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 182.76.82.166/32

  Secgroup2:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: test security group
      GroupName: testsg2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 182.76.82.166/32